from __future__ import annotations

from typing import Any, Dict, Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


def export_pdf_fitted(self, data: Any, output_path, metadata: Optional[Dict[str, Any]] = None) -> None:
    """PDF export with wrapped cells, bounded column widths and repeated headers."""
    dataframe = self._to_dataframe(data)
    title = metadata.get("title", "FORGE Results") if metadata else "FORGE Results"
    subtitle = metadata.get("subtitle", "Industrial Product Intelligence") if metadata else "Industrial Product Intelligence"

    document = SimpleDocTemplate(
        str(output_path),
        pagesize=landscape(A4),
        rightMargin=10 * mm,
        leftMargin=10 * mm,
        topMargin=10 * mm,
        bottomMargin=10 * mm,
        title=str(title),
        author="Team FORGE",
    )

    styles = getSampleStyleSheet()
    title_style = styles["Title"]
    body_style = ParagraphStyle("ForgePDFBody", parent=styles["BodyText"], fontName="Helvetica", fontSize=6.2, leading=7.4, spaceAfter=0)
    header_style = ParagraphStyle("ForgePDFHeader", parent=body_style, fontName="Helvetica-Bold", fontSize=6.4, leading=7.6)
    small_style = ParagraphStyle("ForgePDFSmall", parent=styles["Normal"], fontSize=7.5, leading=9)

    story = [
        Paragraph(self._escape_pdf(title), title_style),
        Paragraph(self._escape_pdf(subtitle), small_style),
        Spacer(1, 5 * mm),
    ]

    if metadata:
        for key, value in metadata.items():
            if key in {"title", "subtitle"}:
                continue
            story.append(Paragraph(self._escape_pdf(f"{key}: {value}"), small_style))
        story.append(Spacer(1, 3 * mm))

    headers = [str(column) for column in dataframe.columns]
    max_columns = 12
    if len(headers) > max_columns:
        headers = headers[:max_columns]
        dataframe = dataframe[headers]

    rows = [[Paragraph(self._escape_pdf(column), header_style) for column in headers]]
    for _, row in dataframe.iterrows():
        rows.append([
            Paragraph(
                self._escape_pdf(self._truncate(self._display_value(row.get(column, "")), 180)),
                body_style,
            )
            for column in headers
        ])

    page_width = landscape(A4)[0] - (20 * mm)
    column_width = page_width / max(1, len(headers))
    table = Table(rows, colWidths=[column_width] * len(headers), repeatRows=1, hAlign="LEFT")
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#eeeeee")),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cccccc")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 3),
        ("RIGHTPADDING", (0, 0), (-1, -1), 3),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]))
    story.append(table)
    story.append(Spacer(1, 5 * mm))
    story.append(Paragraph(f"Generated by {self._escape_pdf('FORGE')} · {self._escape_pdf(__import__('config').CREATOR_YEAR)}", small_style))
    document.build(story)
